### ISSUE TITLE
Docker buid fail on v1.0.100

### ISSUE THREAD

**Issue by bliiitz** [ElrondNetwork/elrond-go#1346]
Hi, 
I'm currently building the docker image of v1.0.100 of elrond node.
During application build i got this error:

```bash
go: verifying github.com/ElrondNetwork/elrond-vm@v0.0.25: checksum mismatch
 	downloaded: h1:px7nyo0okxOH5jm9r+M2On6SEBWipB+Fv6hZ5sVfPjA=
 	go.sum:     h1:FIALKEneTS6BsGgdKDUx16w81S1MvwYnLcaH4o5BMtw=
 The command '/bin/sh -c GO111MODULE=on go mod vendor' returned a non-zero code: 1
```

the gitlab-ci build:
```yaml
variables:
  REGISTRY_URL: "registry.gitlab.com"
  PROJECT_PATH: "bliiitz-corp/elrond/docker-image"
  VERSION: "v1.0.100"

build:
  stage: build
  script:
    - apk add git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_URL
    - git clone --branch $VERSION https://github.com/ElrondNetwork/elrond-go.git 
    - cd elrond-go/
    - docker build -f docker/elrond/Dockerfile --no-cache -t $REGISTRY_URL/$PROJECT_PATH:$VERSION .
    - docker push $REGISTRY_URL/$PROJECT_PATH:$VERSION
  only:
    - master
```

Thank you in advance for your help
