### ISSUE TITLE
[BUG] Testnet node fails to connect to network

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/elrond-go#3371]
I am running the testnet using the following Docker set up based on the manually looked up latest version from Docker Hub.

Note that the testnet node documentation does not cover what version of the node you should use and are currently broken: https://github.com/ElrondNetwork/elrond-go/issues/3366

```yaml
version: '3'

#
# Connect to Elrond testnet, bind RPC port to 127.0.0.1:9999
#
services:
  # https://docs.elrond.com/validators/testnet/use-docker-testnet/
  # https://hub.docker.com/r/elrondnetwork/elrond-go-node-testnet
  elrond:
    image: elrondnetwork/elrond-go-node-testnet:T1.2.11.0
    restart: always
    container_name: elrond
    network_mode: host
    command: --port 37373 --rest-api-interface 127.0.0.1:9999
    volumes:
      - ./validator.pem:/go/elrond-go/cmd/node/config/validatorKey.pem
```

The node connection to the testnet is flaky. I managed to have the node to connect to the network only once out of the 10 attempts. However **it connected to the network once.**

This is how the start up fails:

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
elrond is up-to-date
Attaching to elrond
elrond    | INFO [2021-08-23 11:48:39.010]   starting node                            version = v1.2.11-0-g6e2bf7a70/go1.15.7/linux-amd64/f9b031042e pid = 1
elrond    | INFO [2021-08-23 11:48:39.026]   start time                               formatted = Wed Aug 18 15:00:00 UTC 2021 seconds = 1629298800
elrond    | INFO [2021-08-23 11:48:39.067]   listening on addresses                   addr0 = /ip4/135.181.133.174/tcp/37373/p2p/16Uiu2HAmCMK9oXzNDNFuXiLQwRWWjgnzRcF974JeRS6yyc4GYjhU addr1 = /ip4/127.0.0.1/tcp/37373/p2p/16Uiu2HAmCMK9oXzNDNFuXiLQwRWWjgnzRcF974JeRS6yyc4GYjhU
elrond    | INFO [2021-08-23 11:48:39.068]   started the network discovery process...
elrond    | INFO [2021-08-23 11:48:39.068]   waiting 20 seconds for network discovery...
elrond    | INFO [2021-08-23 11:48:59.069]   starting as observer node
elrond    | INFO [2021-08-23 11:48:59.069]   shard info                               started in shard = metachain
elrond    | INFO [2021-08-23 11:49:59.461]   new nodes config is set for epoch        epoch = 0
elrond    | ERROR[2021-08-23 11:50:59.464]   bootstrapDataComponentsFactory create() failed: bootstrap process has failed: time is out
elrond    | INFO [2021-08-23 11:50:59.765]   starting node                            version = v1.2.11-0-g6e2bf7a70/go1.15.7/linux-amd64/f9b031042e pid = 1
elrond    | INFO [2021-08-23 11:50:59.782]   start time                               formatted = Wed Aug 18 15:00:00 UTC 2021 seconds = 1629298800
elrond    | INFO [2021-08-23 11:50:59.823]   listening on addresses                   addr0 = /ip4/135.181.133.174/tcp/37373/p2p/16Uiu2HAmB57NA91YDSGwgg5xfeb9H1S7Cur5QG6kWFfwYg8SssK5 addr1 = /ip4/127.0.0.1/tcp/37373/p2p/16Uiu2HAmB57NA91YDSGwgg5xfeb9H1S7Cur5QG6kWFfwYg8SssK5
elrond    | INFO [2021-08-23 11:50:59.823]   started the network discovery process...
elrond    | INFO [2021-08-23 11:50:59.823]   waiting 20 seconds for network discovery...
elrond    | INFO [2021-08-23 11:51:19.824]   starting as observer node
elrond    | INFO [2021-08-23 11:51:19.824]   shard info                               started in shard = metachain
elrond    | INFO [2021-08-23 11:52:20.181]   new nodes config is set for epoch        epoch = 0
elrond    | ERROR[2021-08-23 11:53:20.184]   bootstrapDataComponentsFactory create() failed: bootstrap process has failed: time is out
elrond    | INFO [2021-08-23 11:53:20.500]   starting node                            version = v1.2.11-0-g6e2bf7a70/go1.15.7/linux-amd64/f9b031042e pid = 1
elrond    | INFO [2021-08-23 11:53:20.518]   start time                               formatted = Wed Aug 18 15:00:00 UTC 2021 seconds = 1629298800
elrond    | INFO [2021-08-23 11:53:20.559]   listening on addresses                   addr0 = /ip4/135.181.133.174/tcp/37373/p2p/16Uiu2HAkxMosAzi7NH9W3CwfcvzcR7HKp7U9tSifqxm2brkJ6Mhy addr1 = /ip4/127.0.0.1/tcp/37373/p2p/16Uiu2HAkxMosAzi7NH9W3CwfcvzcR7HKp7U9tSifqxm2brkJ6Mhy
elrond    | INFO [2021-08-23 11:53:20.559]   started the network discovery process...
elrond    | INFO [2021-08-23 11:53:20.559]   waiting 20 seconds for network discovery...
elrond    | INFO [2021-08-23 11:53:40.560]   starting as observer node
elrond    | INFO [2021-08-23 11:53:40.560]   shard info                               started in shard = metachain



elrond    | INFO [2021-08-23 11:54:41.393]   new nodes config is set for epoch        epoch = 0
elrond    | ERROR[2021-08-23 11:55:41.396]   bootstrapDataComponentsFactory create() failed: bootstrap process has failed: time is out
```
